# Generated by Django 4.1.7 on 2023-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='attending', to='events.event'),
        ),
    ]
